name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.2, 7.4, 8.0]
        laravel: [^6.0, ^7.0, ^8.0]
        exclude:
          # Exclude laravel 8 on php 7.2 as it requires php 7.3+
          - php: 7.2
            laravel: ^8.0

    name: Run Test (P${{ matrix.php }} - L${{ matrix.laravel }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress
      - name: Execute tests
        run: vendor/bin/phpunit --verbose --testdox
        env:
          FIXERIO_API_KEY: ${{ secrets.FIXERIO_API_KEY }}
          

      - name: Upload artifacts (on failure)
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: ./storage/logs
